MASK_PRE_SYNAPTIC_NEURON = 1
MASK_SYNAPTIC_CLEFT = 2
MASK_POST_SYNAPTIC_NEURON = 3

MASK_INTEGER_VALUES = [
    MASK_PRE_SYNAPTIC_NEURON,
    MASK_SYNAPTIC_CLEFT,
    MASK_POST_SYNAPTIC_NEURON]

INPUT_DATA_INTENSITY_CHANNEL = 0
INPUT_DATA_MASK_CHANNEL = 1
